### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [larrythemodder/plantmegapack-source#11]
[18:07:14] [Client thread/INFO]: Setting user: Aimee_Boy
[18:07:19] [Client thread/WARN]: Skipping bad option: lastServer:
[18:07:19] [Client thread/INFO]: LWJGL Version: 2.9.4
[18:07:25] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Treecapitator, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Plant Mega Pack 1.10 Port BETA, FMLFileResourcePack:Spartan Shields, FMLFileResourcePack:StatusEffectHUD
[18:07:28] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:07:28] [Thread-9/INFO]: Initializing LWJGL OpenAL
[18:07:28] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:07:28] [Thread-9/INFO]: OpenAL initialized.
[18:07:29] [Sound Library Loader/INFO]: Sound engine started
[18:07:34] [Client thread/INFO]: Created: 16x16 textures-atlas
[18:07:41] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Treecapitator, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Plant Mega Pack 1.10 Port BETA, FMLFileResourcePack:Spartan Shields, FMLFileResourcePack:StatusEffectHUD
[18:07:42] [Client thread/INFO]: SoundSystem shutting down...
[18:07:42] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[18:07:42] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:07:42] [Thread-11/INFO]: Initializing LWJGL OpenAL
[18:07:42] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:07:47] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[18:07:47] [Thread-11/INFO]: OpenAL initialized.
[18:07:47] [Sound Library Loader/INFO]: Sound engine started
[18:07:52] [Client thread/WARN]: Skipping bad option: lastServer:
[18:07:59] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:08:13] [Client thread/INFO]: Deleting level New World-
[18:08:13] [Client thread/INFO]: Attempt 1...
[18:08:16] [Client thread/INFO]: Deleting level New World
[18:08:16] [Client thread/INFO]: Attempt 1...
[18:08:20] [Server thread/INFO]: Starting integrated minecraft server version 1.10.2
[18:08:20] [Server thread/INFO]: Generating keypair
[18:08:22] [Server thread/INFO]: Preparing start region for level 0
[18:08:23] [Server thread/INFO]: Preparing spawn area: 5%
[18:08:24] [Server thread/INFO]: Preparing spawn area: 7%
[18:08:25] [Server thread/INFO]: Preparing spawn area: 11%
[18:08:26] [Server thread/INFO]: Preparing spawn area: 16%
[18:08:27] [Server thread/INFO]: Preparing spawn area: 20%
[18:08:28] [Server thread/INFO]: Preparing spawn area: 25%
[18:08:29] [Server thread/INFO]: Preparing spawn area: 30%
[18:08:30] [Server thread/INFO]: Preparing spawn area: 34%
[18:08:31] [Server thread/INFO]: Preparing spawn area: 40%
[18:08:32] [Server thread/INFO]: Preparing spawn area: 45%
[18:08:33] [Server thread/INFO]: Preparing spawn area: 49%
[18:08:34] [Server thread/INFO]: Preparing spawn area: 53%
[18:08:35] [Server thread/INFO]: Preparing spawn area: 58%
[18:08:36] [Server thread/INFO]: Preparing spawn area: 63%
[18:08:37] [Server thread/INFO]: Preparing spawn area: 68%
[18:08:38] [Server thread/INFO]: Preparing spawn area: 73%
[18:08:39] [Server thread/INFO]: Preparing spawn area: 78%
[18:08:40] [Server thread/INFO]: Preparing spawn area: 83%
[18:08:41] [Server thread/INFO]: Preparing spawn area: 87%
[18:08:42] [Server thread/INFO]: Preparing spawn area: 92%
[18:08:43] [Server thread/INFO]: Preparing spawn area: 97%
[18:08:44] [Server thread/INFO]: Changing view distance to 8, from 10
[18:08:48] [Server thread/INFO]: Aimee_Boy[local:E:a17df3f0] logged in with entity id 2154 at (185.5, 61.0, 243.5)
[18:08:48] [Server thread/INFO]: Aimee_Boy joined the game
[18:08:50] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2005ms behind, skipping 40 tick(s)
[18:08:53] [Server thread/INFO]: Saving and pausing game...
[18:08:53] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[18:08:53] [Client thread/INFO]: [CHAT] A new §eOptiFine§f version is available: §eHD Ultra D2§f
[18:08:55] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[18:08:55] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[18:08:55] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@51595d[id=4090b8a2-fe0a-0d64-87ac-f17f0ed250d7,name=Aimee_Boy,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:59) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:56) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:165) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.Minecraft.func_181037_M(Minecraft.java:2907) [bcx.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106) [bxk$3.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[18:09:18] [Server thread/INFO]: Aimee_Boy has just earned the achievement [Taking Inventory]
[18:09:18] [Client thread/INFO]: [CHAT] Aimee_Boy has just earned the achievement [Taking Inventory]
[18:10:09] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2202ms behind, skipping 44 tick(s)
[18:10:58] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2056ms behind, skipping 41 tick(s)
[18:11:01] [Server thread/INFO]: Stopping server
[18:11:01] [Server thread/INFO]: Saving players
[18:11:01] [Server thread/INFO]: Saving worlds
[18:11:01] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[18:11:01] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[18:11:01] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[18:11:03] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Exception while adding particle
	at net.minecraft.world.World.func_72939_s(World.java:1763) ~[aid.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:218) ~[aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:836) ~[aid.class:?]
	at plantmegapack.block.PMPBlockLeaves$1.func_186720_a(PMPBlockLeaves.java:155) ~[PMPBlockLeaves$1.class:?]
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:167) ~[bdg.class:?]
	at net.minecraft.client.particle.ParticleDigging.func_187154_b(SourceFile:52) ~[bnf.class:?]
	at net.minecraft.client.particle.ParticleDigging.func_174845_l(SourceFile:47) ~[bnf.class:?]
	at net.minecraft.client.particle.ParticleDigging$Factory.func_178902_a(SourceFile:105) ~[bnf$a.class:?]
	at net.minecraft.client.particle.ParticleManager.func_178927_a(ParticleManager.java:144) ~[bms.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_174974_b(RenderGlobal.java:2995) ~[boh.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180442_a(RenderGlobal.java:2880) ~[boh.class:?]
	at net.minecraft.world.World.func_175720_a(World.java:1092) ~[aid.class:?]
	at net.minecraft.world.World.func_175688_a(World.java:1079) ~[aid.class:?]
	at net.minecraft.entity.Entity.func_174808_Z(Entity.java:1146) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_174830_Y(Entity.java:1132) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:436) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216) ~[sf.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:167) ~[bnn.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) ~[aid.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) ~[aid.class:?]
	... 10 more

**Comment by larrythemodder** [comment]
That's strange. Does this occur when you create a new world with PMP?

**Comment by mgdgfbhevdyeh** [comment]
sometimes
