### ISSUE TITLE
Crash when looking in water

### ISSUE THREAD

**Issue by tetsune** [larrythemodder/plantmegapack-source#2]
Don't know if you're still working on this, but after working around everything, PMP seems to be an issue in my world. I get a crash when I jump in the water and look down (specifically).

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/5/16 4:17 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2724)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2724)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['iTetsune'/53178, l='MpServer', x=-303.50, y=58.40, z=341.63], EntityOtherPlayerMP['BritishMindslave'/255, l='MpServer', x=-313.57, y=68.00, z=322.49]]
	Chunk stats: MultiplayerChunkCache: 288, 288
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-204,64,252), Chunk: (at 4,4,12 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 600085 game time, 538785 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntityOtherPlayerMP['BritishMindslave'/255, l='MpServer', x=-313.57, y=68.00, z=322.49], EntityPlayerSP['iTetsune'/53178, l='MpServer', x=-303.50, y=58.40, z=341.63], EntityVillager['Margorie'/63116, l='MpServer', x=-312.46, y=65.00, z=332.13], EntityZombie['Zombie'/66866, l='MpServer', x=-313.26, y=36.00, z=324.54], EntitySheep['Sheep'/53, l='MpServer', x=-294.20, y=66.00, z=282.77], EntityPig['Pig'/54, l='MpServer', x=-296.11, y=61.77, z=316.10], EntityPig['Pig'/55, l='MpServer', x=-284.85, y=62.30, z=340.46], EntityPig['Pig'/66, l='MpServer', x=-300.59, y=66.00, z=278.70], EntitySheep['Sheep'/72, l='MpServer', x=-280.17, y=64.00, z=281.45], EntityVillager['Armandina'/18381, l='MpServer', x=-297.42, y=64.00, z=351.77], EntitySquid['Squid'/66638, l='MpServer', x=-350.91, y=61.73, z=316.99], EntityOtherPlayerMP['BritishMindslave'/255, l='MpServer', x=-315.36, y=65.00, z=331.15], EntityHorse['Donkey'/86, l='MpServer', x=-259.81, y=68.00, z=390.56], EntityHorse['Donkey'/87, l='MpServer', x=-264.85, y=66.00, z=397.92], EntitySheep['Sheep'/102, l='MpServer', x=-244.55, y=68.00, z=271.19], EntityPig['Pig'/103, l='MpServer', x=-239.74, y=67.00, z=280.46], EntityHorse['Horse'/105, l='MpServer', x=-253.02, y=65.00, z=397.89], EntityPig['Pig'/120, l='MpServer', x=-223.89, y=69.00, z=278.88], EntityPig['Pig'/121, l='MpServer', x=-229.49, y=68.00, z=278.78], EntityHorse['Horse'/122, l='MpServer', x=-237.61, y=62.71, z=381.88], EntityOtherPlayerMP['BritishMindslave'/255, l='MpServer', x=-313.57, y=68.00, z=322.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1821104240 bytes (1736 MB) / 3532128256 bytes (3368 MB) up to 3532128256 bytes (3368 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3431m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2076 Optifine OptiFine_1.10.2_HD_U_C3 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2076.jar) 
	UCHIJA	Forge{12.18.1.2076} [Minecraft Forge] (forge-1.10.2-12.18.1.2076.jar) 
	UCHIJA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.0.3.jar) 
	UCHIJA	movillages{1.5.2} [Mo' Villages] ([1.9.4]Mo' Villages-1.5.2.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJA	JEI{3.9.0.246} [Just Enough Items] (jei_1.10.2-3.9.0.246.jar) 
	UCHIJA	appleskin{1.0.2} [AppleSkin] (AppleSkin-mc1.10.2-1.0.2.jar) 
	UCHIJA	Aroma1997CoreHelper{1.1.0.3} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.0.3.jar) 
	UCHIJA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.1.jar) 
	UCHIJA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJA	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCHIJA	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCHIJA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJA	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UCHIJA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2078} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2078-universal.jar) 
	UCHIJA	blockdrops{1.0.10} [Block Drops] (BlockDrops-1.10.2-1.0.10.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJA	BloodMagic{1.9.4-2.0.4-58} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.4-58.jar) 
	UCHIJA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJA	cosmeticarmorreworked{1.10.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v1a.jar) 
	UCHIJA	craftingtweaks{6.1.12} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.12.jar) 
	UCHIJA	disenchanter{1.4} [Disenchanter] (disenchanter-[1.9.4]1.4.jar) 
	UCHIJA	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	flowergirls{1.10.2-1.1.0} [Ender Flowergirls] (flowergirls-1.10.2-1.1.0.jar) 
	UCHIJA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
	UCHIJA	gravestone{1.5.5} [Gravestone] (GraveStone Mod 1.5.5.jar) 
	UCHIJA	Harvest{1.10.2-1.1.0-10} [Harvest] (Harvest-1.10.2-1.1.0-10.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	jeresources{0.5.0.52} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.0.52.jar) 
	UCHIJA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJA	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHIJA	shear{1.1.2} [More Shearables] (MoreShearables1.2.1-1.10.2.jar) 
	UCHIJA	nmsot{1.1.7-mc[1.9.4-1.10.2]} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.7-mc[1.9.4-1.10.2].jar) 
	UCHIJA	recipehandler{0.5} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.5(1.10.2).jar) 
	UCHIJA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
	UCHIJA	plantmegapack{1.9.8} [Plant Mega Pack 1.10 Port BETA] (plantmegapack-1.10.0-beta.jar) 
	UCHIJA	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJA	platforms{1.2.0} [Platforms] (platforms-1.10.0-1.2.0.jar) 
	UCHIJA	packchevsky{b6} [Potion Packs] (PotionPacks_1.10_b6b.jar) 
	UCHIJA	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCHIJA	xreliquary{1.10.2-1.3.3.521} [Reliquary] (Reliquary-1.10.2-1.3.3.521.jar) 
	UCHIJA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJA	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJA	villagebox{0.5.0} [Village Box] (villagebox-1.10.2-0.5.0.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	WailaHarvestability{1.1.8} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.8.jar) 
	UCHIJA	waterstrainer{1.2.1} [Water Strainer] (WaterStrainer-1.9.4-1.2.1.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJA	XaeroMinimap{1.10.4} [Xaero's Minimap] (Xaeros_Minimap_1.10.4_Forge_1.10.2.jar) 
	UCHIJA	YAFM{1.0.5} [Yet Another Food Mod] (yafm-1.0.5-mc1.9.4.jar) 
	UCHIJA	YALSM{2.1.6} [Yet Another Leather Smelting Mod] (yalsm-2.1.6-mc1.9.4.jar) 
	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
  
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Launched Version: forge-12.18.1.2076
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Doku Mod Support 1.10.zip, 1.10-Dokucraft-TSC-Light.zip, BiomesOPlenty-DokucraftTSC-1.10.2_03.zip, JEI Textures.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4229
	OpenGlRenderer: Intel(R) HD Graphics 3000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by tetsune** [comment]
Seems to be an issue with the aquatic plants. :c

**Comment by larrythemodder** [comment]
Sorry for taking so long to reply, @tetsune ! I've been on hiatus from modding! I will take a look at this issue when I get my modding rig all set up again.

**Comment by tetsune** [comment]
@larrythemodder 
Thanks for the update! I understand we all need a break, so it's alright. It's the submerged plants generally, and I haven't run into problems with other ones.

**Comment by larrythemodder** [comment]
@tetsune Submerged plants are now good to go! Just avoid floating plants, I'm still working on those.

**Comment by durand1w** [comment]
Larry, thanks for all the work you have done on this.  I saw the new about 10paks new mod development as well.  I just got to a point to work on this today.  I fixed the water crash above, plus made a minor improvement for submerged plants and corals.

The crash is caused by a null pointer when drawing the selection bounding box.  Corals would not crash since they had a bounding box defined.  Non-corals were set to Blocks.NULL_AABB.  I replaced that with a small flat bounding box and have no issues now.  I also added the bit below to make them pop-off if the block below is broken.  I have a small list of other fixes as well, but I'll post those later if I figure out the double plant render issue.

-PMPBlockSubmerged has getSelectedBoundingBox for non-coral blocks = Block.NULL_AABB  I created a new Bounding Box for this and replaced it Block.NULL_AABB with SUBMERGED_BLOCK_AABB
public static final AxisAlignedBB SUBMERGED_BLOCK_AABB = new AxisAlignedBB(0.375D, 0.375D, 0.0D, 0.625D, 0.0625D, 0.625D);

-Collision also needs updated with the same logic so that you can pass through/over non-corals
		if (this.plantData.attributes.category == PMPPlantCategory.cora) {
			return Block.FULL_BLOCK_AABB;
		}
		else return SUBMERGED_BLOCK_AABB;

-Also, these should break if the block below is broken, so I added this to the bottom of the class

   private boolean canBePlacedOn(World worldIn, BlockPos pos)
    {
    	return worldIn.getBlockState(pos.up()).isFullyOpaque();
    }
    
    /**
     * Called when a neighboring block was changed and marks that this state should perform any checks during a neighbor
     * change. Cases may include when redstone power is updated, cactus blocks popping off due to a neighboring solid
     * block, etc.
     */
    public void neighborChanged(IBlockState state, World worldIn, BlockPos pos, Block blockIn)
    {
        if (!this.canBePlacedOn(worldIn, pos))
        {
            this.dropBlockAsItem(worldIn, pos, state, 0);
            worldIn.setBlockToAir(pos);
        }
    }

**Comment by larrythemodder** [comment]
@durand1w Hey, thanks for the help. I see you've noticed the new RealWorld mod coming out, so I won't be checking this repo much. If you want to go ahead and push the changes, I'd be happy to merge them. However, I don't think development is gonna continue with this project.

**Comment by durand1w** [comment]
No worries.  I'm curious to see where things go with his new mod.  I do like the fact that the mod in this form is working on 1.10.2, I have access to fix issues and I know that you can regen old maps with the World Generation Manager.  Seeing plants and new trees added to a world that has survived since Beta is really nice.  Thanks again for your efforts.
